# Generated by Django 3.2.14 on 2022-07-30 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0003_userlikedislikepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userlikedislikepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes_dislikes', to='panel.post'),
        ),
        migrations.AlterField(
            model_name='userlikedislikepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_disliked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
