# Generated by Django 3.2.14 on 2022-08-02 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_ticketmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='post_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv']), panel.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='panel.ticket'),
        ),
    ]
